### ISSUE TITLE
Fix windows network online indicator

### ISSUE THREAD

**Issue by rs** [nextdns/windows#1]
```
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\POLICIES\MICROSOFT\Windows\NetworkConnectivityStatusIndicator" /v UseGlobalDNS /t REG_DWORD /d 1 /f
```

**Comment by SoMuchToGrok** [comment]
To add some color re: potential urgency of this issue - Microsoft Outlook uses this networking status and makes some assumptions about connectivity to IMAP/POP servers. Without this fix applied, it causes routine errors in Outlook which ultimately leads to a bad UX.

**Comment by catwithbanana** [comment]
This is still broken. The network icon sometimes shows no connection even while the internet is working fine. Please fix this.

**Comment by fantom-x** [comment]
This seems to have stopped working as of Windows 10 21H1. Is there another way to fix the issue?
