### ISSUE TITLE
NextDNS not enabled on startup

### ISSUE THREAD

**Issue by infocilla** [nextdns/windows#12]
Hi,
I noticed that when I start my computer (Win10), and right click on the tray icon, it seems that NextDNS is not enabled (option is "Enable"). When I cliock on "Enable" it doesn't enable. I need to restart NextDNS service manually to make it work.
WOuld it be possible to fix this ?
Thanks
Romain

**Comment by 73F0SG1R** [comment]
i have have this issue - very annoying

affects both windows 10 & 11

the windows agent installs fine and starts by default after reboot, etc., but does not stay enabled

have to manually right-click enable to get it to work - this is an annoying bug

i have tried to install the agent on computers that i manage/own but don't use (employees, family, etc.)

it should enable by default, or at the very least be an option in the setup
