### ISSUE TITLE
Enable/Disable broken

### ISSUE THREAD

**Issue by olsonperrensen** [nextdns/windows#14]
Buttons do nothing. 

` NextDNS starts out in a weird state where it is enabled (as verified by the NextDNS website itself, along with the blocklists being active), yet the tray icon's right-click menu says "Enable". Clicking it does nothing. Hitting "Quit" will close the app, but the NextDNS configuration remains.

The only way I've found to temporarily get out of this weird state is to manually Disable then Enable the TAP-Windows Adapter V9 used by NextDNS in my network settings. Only lasts until the next boot, then needs to be done again.

This is a new installation of Windows 10 on a new laptop. Reinstalling NextDNS but it doesn't change anything. Tried removing the adapter to see if a fresh NextDNS installation would also reinstall the adapter, and it didn't (just gives me an error, "getTuntapComponentId: not found component id"), so I just brought it back with system restore.

Any ideas how to proceed?

Thanks! `

See : https://help.nextdns.io/t/m1hp273/cant-disable-nextdns-on-windows-10-without-manually-restarting-tap-adapter

A fellow user wrote for more context. 

Thanks.

**Comment by gpdevsoft** [comment]
i have the same problem, and either i'm using nextdns on fresh install windows 10 pro

**Comment by ijuliank** [comment]
this issue is still there

**Comment by rs** [comment]
Will be fixed with v3.0.0
