### ISSUE TITLE
Uninstaller says installation failed

### ISSUE THREAD

**Issue by bigdargon** [nextdns/windows#23]
After a failed beta 3.0 install I uninstalled but the uninstaller said install failed.

![Screenshot 2022-05-31 104602](https://user-images.githubusercontent.com/10969626/171089342-4e48c580-455e-425c-be5e-2aaf0cb861ee.png)

After the uninstallation is complete, the desktop icon has not been removed.

![Screenshot 2022-05-31 104653](https://user-images.githubusercontent.com/10969626/171089398-b1f390c8-31dd-41af-a688-6341f0427ee3.png)

**Comment by Delaire** [comment]
Hello, I can reproduce your issue, its coming from https://github.com/nextdns/windows/blob/43340205e2ad1cf1027d97bd6f027311870b24c0/nsis/NextDNSSetup.nsi#L182
Ill have a look to see how it can be fixed

**Comment by bigdargon** [comment]
@Delaire Nice! Thanks!
