### ISSUE TITLE
Nextdns official website blocked

### ISSUE THREAD

**Issue by trimechee** [nextdns/windows#40]
Hello, thank you so much for this amazing awesome DNS ! 👏👏🔥 I just noticed that when i enable beta option "AI-based threat detection", Nextdns official site doesn't work anymore and Nextdns offical website is blocked :( 

https://nextdns.io/en

surely a false positive, it will be good if this bug is solved :)

**Comment by rs** [comment]
Make sure you remove the /en at the end of the URL. This domain is not blocked by AI threat.

In the future, please use https://help.nextdns.io for bug reports on the service. This repository is dedicated to the windows client.
