### ISSUE TITLE
Affiliate Links do not work despite beign allowed and whitelisted

### ISSUE THREAD

**Issue by wackyp** [nextdns/windows#5]
I have email newsletters etc that I WANT to click the links within and have enabled affiliate tracking and allowed certain troublesome 'click' urls manually but I continue to get the message the 'great this url is no longer blocked... refresh dns and come back later etc"...

... but it NEVER gets unblocked... despite being on the allowlist. how does this get fixed?

**Comment by rs** [comment]
Please use our community support to post issues about the service. This repository is for bug regarding the windows client.

https://help.nextdns.io/category/community
