### ISSUE TITLE
Name resolution broken when running app

### ISSUE THREAD

**Issue by catwithbanana** [nextdns/windows#6]
When the NextDNS app is running name resolution is broken on my Windows PC. This happened on two different devices beginning yesterday afternoon.

Services like email load just fine, and the network indicator shows an internet connection, but websites do not load. Running the Windows Network diagnostic tool reports that DNS is not functioning properly.

Restarting the computer does not solve the issue. Restarting the app _sometimes_ solves the issue. Closing the app and running NextDNS configs through Windows settings or at the router level does solve the issue. So the issue is with the app itself or something it does with the network configuration.

This is in addition to the previously reported issue where Windows sometimes shows no connection when using NextDNS even when the internet is working just fine.

Please let me know if you have any further questions I can help with. Thanks!

**Comment by bigdargon** [comment]
Same problem. Both of my computers (running win 8.1 and win 10) get a DNS not resolved error when using nextdns. I disabled nextdns then everything works properly!

**Comment by himanshuchandola** [comment]
I added 2 domains to allow list that solved my issue
`msftconnecttest.com`
`msftconnect.com`
This  2 urls are queried by Windows to determine if the. computer is connected to the Internet.

not sure if there are others but for me these 2 did the work. Check them out
