### ISSUE TITLE
Windows issue

### ISSUE THREAD

**Issue by valdrinium** [nextdns/windows#7]
I get this issue when trying to enable NextDns
![image](https://user-images.githubusercontent.com/30521006/123161928-b1422c00-d478-11eb-9577-597cccbefdd3.png)
What additional information do you need for debugging?

**Comment by rs** [comment]
What do you get in event viewer for nextdns service?

**Comment by Lugribossk** [comment]
I have the same problem. I can't seem to find anything related to NextDNS in the event viewer, and it's not in the Services list either.

**Comment by rs** [comment]
Please try reinstalling it then, the service not running is the cause of this message. Something is potentially preventing the service from running.

**Comment by Lugribossk** [comment]
It looks like installing the service fails:
![image](https://user-images.githubusercontent.com/1399482/124387419-e6ebde00-dcde-11eb-9449-62b2d9ea07b7.png)
This is with the NextDNSSetup-2.1.0.exe installer.

**Comment by rs** [comment]
Are you admin on that system?

**Comment by Lugribossk** [comment]
Yes, it says "Administrator - Local Account" under Settings. The installer also pops up the UAC prompt at the start, and trying to run it as administrator doesn't change anything.

**Comment by brainsik** [comment]
I'm also having this problem. After months of working, it's now stuck in this state. I've uninstalled completely, including the tap driver/interface (which the uninstaller doesn't remove), rebooted, and generally done various IT dances (repeatedly) to try to get it to work again. I don't have the time to wipe the box and start from scratch.

The NextDNS forums have a couple issues (e.g., [Windows 10 - cannot enable NextDNS. "An Error Append while trying to communicate with NextDNS Windows Service"](https://help.nextdns.io/t/h7hf9v4/windows-10-cannot-enable-nextdns-an-error-append-while-trying-to-communicate-with-nextdns-windows-service)) about this and they end with folks recommending YogaDNS (a closed source DNS client) which I'm not interested in. I'd like for the official client to work with the paid service.

I'd be happy to provide logs or whatever could help figure this out.

**Comment by abtre78** [comment]
Nextdns have a lot issues on Windows PC. You can try Yogadns.

**Comment by tanji** [comment]
I had the same issue and I found a fix. I guess that is caused by previous installs/upgrades; the service won't install if the EventLog registry key still exists, and the uninstaller does not delete that key. The steps are as follows:

1. Uninstall NextDns 
2. Open Registry Editor
3. Navigate to the following key: Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\NextDNSService
4. Right click the key in left pane
5. Click "Delete"
6. Reinstall NextDNS

**Comment by rs** [comment]
Thanks for the tips @tanji

**Comment by brainsik** [comment]
> I had the same issue and I found a fix.

Thank you, @tanji! Your instructions fixed my problem and I'm finally running NextDNS on a Windows host after months of being unable to. 🙏🏻
