### ISSUE TITLE
Hide Nextdns from system tray and prevent uninstalling it

### ISSUE THREAD

**Issue by mx202** [nextdns/windows#9]
Hello,
I'm using Nextdns on my son's computer, but he found it and uninstalled it.
Please, consider adding the following abilities:
1. hiding the app from the System Tray on Windows
2.  Preventing editing and uninstalling it from Windows without a specific password.

I hope you do it
Thanks guys

**Comment by rs** [comment]
Please use the https://nextdns.io/cli for that.

**Comment by DutchRiga** [comment]
rs, could you please help to configure "nextdns.conf" file in C:\Program Files\NextDNS path.
def config is:

log-queries false
report-client-info false
bogus-priv true
listen 127.0.0.1:53
detect-captive-portals false
use-hosts true
timeout 5s
max-inflight-requests 256
auto-activate false
control nextdns-cli
cache-max-age 0s
discovery-dns 
hardened-privacy false
setup-router false
cache-size 0
max-ttl 0s

where should I put my nextdns ID?
...............................................................................................
this code what you gave, doesnt work on windows:

C:\\Program Files\NextDNS\nextdns.exe install ^
  -config <your config_id> ^
  -report-client-info ^
  -auto-activate

https://github.com/nextdns/nextdns/wiki/Windows
...............................................................................................
in my CMD I can install nextdns, i can run it, but I cant setup it with my nextdns ID.

Could you please provide more detailed instruction for windows users pls, thx

**Comment by DutchRiga** [comment]
rs, could you please help to configure "nextdns.conf" file in C:\Program Files\NextDNS path.
def config is:

log-queries false
report-client-info false
bogus-priv true
listen 127.0.0.1:53
detect-captive-portals false
use-hosts true
timeout 5s
max-inflight-requests 256
auto-activate false
control nextdns-cli
cache-max-age 0s
discovery-dns 
hardened-privacy false
setup-router false
cache-size 0
max-ttl 0s

where should I put my nextdns ID?
...............................................................................................
this code what you gave, doesnt work on windows:

C:\\Program Files\NextDNS\nextdns.exe install ^
  -config <your config_id> ^
  -report-client-info ^
  -auto-activate

https://github.com/nextdns/nextdns/wiki/Windows
...............................................................................................
in my CMD I can install nextdns, i can run it, but I cant setup it with my nextdns ID.

Could you please provide more detailed instruction for windows users pls, thx

**Comment by rs** [comment]
try `nextdns.exe config set -config xxxxx` then restart nextdns.

**Comment by DutchRiga** [comment]
rs, thanks, now its works :)
